### ISSUE TITLE
Unexpected Identifier with jest

### ISSUE THREAD

**Issue by imerkle** [stellar/js-xdr#28]
When using stellar base library jest shows an error
```
node_modules/js-xdr/src/cursor.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import BaseCursor from 'cursor';
                                                                                                    ^^^^^^^^^^

    SyntaxError: Unexpected identifier

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/ScriptTransformer.js:440:17)
      at Object.<anonymous> (node_modules/js-xdr/lib/cursor.js:10:15)

```

**Comment by imerkle** [comment]
Removing ./src/ from build ouput solves it

**Comment by rloukil** [comment]
can you please tell me how you did it?
