### ISSUE TITLE
How to use this library in standalone NodeJS application

### ISSUE THREAD

**Issue by mahenpatil** [stellar/js-xdr#8]
This is what I get when try doing it:

ReferenceError: window is not defined
    at /Users/mahendra/FixSpec/code/central_validator/node_modules/xdr/lib/ajax.js:131:36
    at Object.<anonymous> (/Users/mahendra/FixSpec/code/central_validator/node_modules/xdr/lib/ajax.js:453:3)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at repl:1:11

**Comment by bartekn** [comment]
```
at /Users/mahendra/FixSpec/code/central_validator/node_modules/xdr/lib/ajax.js:131:36
                                                               ^^^
```
This package name is `js-xdr`: https://www.npmjs.com/package/js-xdr
